title: CoolAJ86
favicon: media/coolaj86-logo-16x16.png
square_logo: media/daplie-logo-final.png
tagline: "I make Awesome. Mostly with node.js!"
description: The rants and raves of AJ the Technologist
base_url: "https://coolaj86.com"
base_path: /
google_analytics_tracking_id: UA-18902063-1
disqus_shortname: coolaj86-gh
theme: daplie-desi-theme
