title: Daplie
favicon: media/daplie-favicon.png
square_logo: media/daplie-logo-final.png
tagline: "Changing the world since 2015"
description: The rants and raves of Daplie
base_url: "https://daplie.com"
base_path: /
google_analytics_tracking_id: UA-68660916-1
disqus_shortname: daplie
theme: daplie
twitter: https://twitter.com/dapliecloud
facebook: https://www.facebook.com/daplie 
google: https://plus.google.com/112399609497136452728
github: https://github.com/Daplie

